/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 11
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  sym_entity = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_quoted_attribute_value_token1 = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_quoted_attribute_value_token2 = 15,
  sym_text = 16,
  anon_sym_LBRACK_PERCENT = 17,
  anon_sym_PERCENT_RBRACK = 18,
  anon_sym_LBRACK_PERCENT_POUND = 19,
  anon_sym_PERCENT = 20,
  anon_sym_PERCENT_POUND = 21,
  sym__start_tag_name = 22,
  sym__script_start_tag_name = 23,
  sym__style_start_tag_name = 24,
  sym__end_tag_name = 25,
  sym_erroneous_end_tag_name = 26,
  sym__implicit_end_tag = 27,
  sym_raw_text = 28,
  sym_comment = 29,
  sym_tt_directive_content = 30,
  sym_tt_line_directive_text = 31,
  sym_document = 32,
  sym_doctype = 33,
  sym__node = 34,
  sym_element = 35,
  sym_script_element = 36,
  sym_style_element = 37,
  sym_start_tag = 38,
  sym_script_start_tag = 39,
  sym_style_start_tag = 40,
  sym_self_closing_tag = 41,
  sym_end_tag = 42,
  sym_erroneous_end_tag = 43,
  sym_attribute = 44,
  sym_quoted_attribute_value = 45,
  sym_tt_block = 46,
  sym_tt_directive = 47,
  sym_tt_comment = 48,
  sym_tt_line = 49,
  sym_tt_line_directive = 50,
  sym_tt_line_comment = 51,
  aux_sym_document_repeat1 = 52,
  aux_sym_start_tag_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [anon_sym_LBRACK_PERCENT] = "[%",
  [anon_sym_PERCENT_RBRACK] = "%]",
  [anon_sym_LBRACK_PERCENT_POUND] = "[%#",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PERCENT_POUND] = "%#",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_tt_directive_content] = "tt_directive_content",
  [sym_tt_line_directive_text] = "tt_line_directive_text",
  [sym_document] = "document",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_tt_block] = "tt_block",
  [sym_tt_directive] = "tt_directive",
  [sym_tt_comment] = "tt_comment",
  [sym_tt_line] = "tt_line",
  [sym_tt_line_directive] = "tt_line_directive",
  [sym_tt_line_comment] = "tt_line_comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [anon_sym_LBRACK_PERCENT] = anon_sym_LBRACK_PERCENT,
  [anon_sym_PERCENT_RBRACK] = anon_sym_PERCENT_RBRACK,
  [anon_sym_LBRACK_PERCENT_POUND] = anon_sym_LBRACK_PERCENT_POUND,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PERCENT_POUND] = anon_sym_PERCENT_POUND,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_tt_directive_content] = sym_tt_directive_content,
  [sym_tt_line_directive_text] = sym_tt_line_directive_text,
  [sym_document] = sym_document,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_tt_block] = sym_tt_block,
  [sym_tt_directive] = sym_tt_directive,
  [sym_tt_comment] = sym_tt_comment,
  [sym_tt_line] = sym_tt_line,
  [sym_tt_line_directive] = sym_tt_line_directive,
  [sym_tt_line_comment] = sym_tt_line_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_directive_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_line_directive_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_block] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_line_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_tt_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 13,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 28,
  [31] = 31,
  [32] = 15,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 33,
  [39] = 14,
  [40] = 34,
  [41] = 35,
  [42] = 18,
  [43] = 19,
  [44] = 20,
  [45] = 21,
  [46] = 22,
  [47] = 23,
  [48] = 24,
  [49] = 26,
  [50] = 27,
  [51] = 36,
  [52] = 37,
  [53] = 31,
  [54] = 29,
  [55] = 55,
  [56] = 56,
  [57] = 55,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 56,
  [65] = 65,
  [66] = 66,
  [67] = 65,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 61,
  [73] = 73,
  [74] = 74,
  [75] = 73,
  [76] = 74,
  [77] = 71,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 70,
  [85] = 69,
  [86] = 68,
  [87] = 80,
  [88] = 82,
  [89] = 89,
  [90] = 90,
  [91] = 83,
  [92] = 89,
  [93] = 93,
  [94] = 94,
  [95] = 93,
  [96] = 94,
  [97] = 97,
  [98] = 78,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 105,
  [109] = 102,
  [110] = 110,
  [111] = 103,
  [112] = 110,
  [113] = 113,
  [114] = 99,
  [115] = 107,
  [116] = 116,
  [117] = 106,
  [118] = 101,
  [119] = 104,
  [120] = 100,
  [121] = 116,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 76,
        '%', 83,
        '&', 3,
        '\'', 73,
        '/', 8,
        '<', 27,
        '=', 30,
        '>', 25,
        '[', 4,
        'D', 12,
        'd', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(76);
      if (lookahead == '\'') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(80);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == '>') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(81);
      END_STATE();
    case 10:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '%' &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '[') ADVANCE(79);
      END_STATE();
    case 18:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '%') ADVANCE(83);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '[') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(79);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '%' &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '[') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACK_PERCENT);
      if (lookahead == '#') ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACK);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACK_PERCENT_POUND);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '#') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_PERCENT_POUND);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 20, .external_lex_state = 2},
  [2] = {.lex_state = 20, .external_lex_state = 3},
  [3] = {.lex_state = 20, .external_lex_state = 3},
  [4] = {.lex_state = 20, .external_lex_state = 3},
  [5] = {.lex_state = 20, .external_lex_state = 3},
  [6] = {.lex_state = 20, .external_lex_state = 2},
  [7] = {.lex_state = 20, .external_lex_state = 3},
  [8] = {.lex_state = 20, .external_lex_state = 2},
  [9] = {.lex_state = 20, .external_lex_state = 4},
  [10] = {.lex_state = 20, .external_lex_state = 5},
  [11] = {.lex_state = 20, .external_lex_state = 4},
  [12] = {.lex_state = 20, .external_lex_state = 5},
  [13] = {.lex_state = 20, .external_lex_state = 3},
  [14] = {.lex_state = 20, .external_lex_state = 2},
  [15] = {.lex_state = 20, .external_lex_state = 2},
  [16] = {.lex_state = 20, .external_lex_state = 3},
  [17] = {.lex_state = 20, .external_lex_state = 2},
  [18] = {.lex_state = 20, .external_lex_state = 2},
  [19] = {.lex_state = 20, .external_lex_state = 2},
  [20] = {.lex_state = 20, .external_lex_state = 2},
  [21] = {.lex_state = 20, .external_lex_state = 2},
  [22] = {.lex_state = 20, .external_lex_state = 2},
  [23] = {.lex_state = 20, .external_lex_state = 2},
  [24] = {.lex_state = 20, .external_lex_state = 2},
  [25] = {.lex_state = 20, .external_lex_state = 3},
  [26] = {.lex_state = 20, .external_lex_state = 2},
  [27] = {.lex_state = 20, .external_lex_state = 2},
  [28] = {.lex_state = 20, .external_lex_state = 2},
  [29] = {.lex_state = 20, .external_lex_state = 2},
  [30] = {.lex_state = 20, .external_lex_state = 3},
  [31] = {.lex_state = 20, .external_lex_state = 3},
  [32] = {.lex_state = 20, .external_lex_state = 3},
  [33] = {.lex_state = 20, .external_lex_state = 2},
  [34] = {.lex_state = 20, .external_lex_state = 3},
  [35] = {.lex_state = 20, .external_lex_state = 3},
  [36] = {.lex_state = 20, .external_lex_state = 3},
  [37] = {.lex_state = 20, .external_lex_state = 3},
  [38] = {.lex_state = 20, .external_lex_state = 3},
  [39] = {.lex_state = 20, .external_lex_state = 3},
  [40] = {.lex_state = 20, .external_lex_state = 2},
  [41] = {.lex_state = 20, .external_lex_state = 2},
  [42] = {.lex_state = 20, .external_lex_state = 3},
  [43] = {.lex_state = 20, .external_lex_state = 3},
  [44] = {.lex_state = 20, .external_lex_state = 3},
  [45] = {.lex_state = 20, .external_lex_state = 3},
  [46] = {.lex_state = 20, .external_lex_state = 3},
  [47] = {.lex_state = 20, .external_lex_state = 3},
  [48] = {.lex_state = 20, .external_lex_state = 3},
  [49] = {.lex_state = 20, .external_lex_state = 3},
  [50] = {.lex_state = 20, .external_lex_state = 3},
  [51] = {.lex_state = 20, .external_lex_state = 2},
  [52] = {.lex_state = 20, .external_lex_state = 2},
  [53] = {.lex_state = 20, .external_lex_state = 2},
  [54] = {.lex_state = 20, .external_lex_state = 3},
  [55] = {.lex_state = 7, .external_lex_state = 6},
  [56] = {.lex_state = 7, .external_lex_state = 6},
  [57] = {.lex_state = 7, .external_lex_state = 6},
  [58] = {.lex_state = 7, .external_lex_state = 6},
  [59] = {.lex_state = 7, .external_lex_state = 6},
  [60] = {.lex_state = 7, .external_lex_state = 2},
  [61] = {.lex_state = 7, .external_lex_state = 6},
  [62] = {.lex_state = 7, .external_lex_state = 2},
  [63] = {.lex_state = 7, .external_lex_state = 2},
  [64] = {.lex_state = 7, .external_lex_state = 2},
  [65] = {.lex_state = 1, .external_lex_state = 2},
  [66] = {.lex_state = 7, .external_lex_state = 2},
  [67] = {.lex_state = 1, .external_lex_state = 2},
  [68] = {.lex_state = 7, .external_lex_state = 6},
  [69] = {.lex_state = 7, .external_lex_state = 6},
  [70] = {.lex_state = 7, .external_lex_state = 6},
  [71] = {.lex_state = 0, .external_lex_state = 7},
  [72] = {.lex_state = 7, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 8},
  [74] = {.lex_state = 0, .external_lex_state = 8},
  [75] = {.lex_state = 0, .external_lex_state = 8},
  [76] = {.lex_state = 0, .external_lex_state = 8},
  [77] = {.lex_state = 0, .external_lex_state = 7},
  [78] = {.lex_state = 0, .external_lex_state = 9},
  [79] = {.lex_state = 0, .external_lex_state = 8},
  [80] = {.lex_state = 5, .external_lex_state = 10},
  [81] = {.lex_state = 0, .external_lex_state = 8},
  [82] = {.lex_state = 5, .external_lex_state = 10},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 7, .external_lex_state = 2},
  [85] = {.lex_state = 7, .external_lex_state = 2},
  [86] = {.lex_state = 7, .external_lex_state = 2},
  [87] = {.lex_state = 5, .external_lex_state = 10},
  [88] = {.lex_state = 5, .external_lex_state = 10},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 8},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 6, .external_lex_state = 2},
  [94] = {.lex_state = 2, .external_lex_state = 2},
  [95] = {.lex_state = 6, .external_lex_state = 2},
  [96] = {.lex_state = 2, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 8},
  [98] = {.lex_state = 0, .external_lex_state = 9},
  [99] = {.lex_state = 0, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 11},
  [101] = {.lex_state = 18, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 5, .external_lex_state = 2},
  [104] = {.lex_state = 5, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 12},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 5, .external_lex_state = 2},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
  [114] = {.lex_state = 0, .external_lex_state = 2},
  [115] = {.lex_state = 0, .external_lex_state = 2},
  [116] = {.lex_state = 0, .external_lex_state = 2},
  [117] = {.lex_state = 0, .external_lex_state = 12},
  [118] = {.lex_state = 18, .external_lex_state = 2},
  [119] = {.lex_state = 5, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 11},
  [121] = {.lex_state = 0, .external_lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT_POUND] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_tt_directive_content] = ACTIONS(1),
    [sym_tt_line_directive_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(113),
    [sym_doctype] = STATE(6),
    [sym__node] = STATE(6),
    [sym_element] = STATE(6),
    [sym_script_element] = STATE(6),
    [sym_style_element] = STATE(6),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(73),
    [sym_style_start_tag] = STATE(76),
    [sym_self_closing_tag] = STATE(28),
    [sym_erroneous_end_tag] = STATE(6),
    [sym_tt_block] = STATE(6),
    [sym_tt_directive] = STATE(53),
    [sym_tt_comment] = STATE(53),
    [sym_tt_line] = STATE(6),
    [sym_tt_line_directive] = STATE(15),
    [sym_tt_line_comment] = STATE(15),
    [aux_sym_document_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_entity] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(15),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(17),
    [anon_sym_PERCENT] = ACTIONS(19),
    [anon_sym_PERCENT_POUND] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_doctype] = STATE(4),
    [sym__node] = STATE(4),
    [sym_element] = STATE(4),
    [sym_script_element] = STATE(4),
    [sym_style_element] = STATE(4),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(75),
    [sym_style_start_tag] = STATE(74),
    [sym_self_closing_tag] = STATE(30),
    [sym_end_tag] = STATE(37),
    [sym_erroneous_end_tag] = STATE(4),
    [sym_tt_block] = STATE(4),
    [sym_tt_directive] = STATE(31),
    [sym_tt_comment] = STATE(31),
    [sym_tt_line] = STATE(4),
    [sym_tt_line_directive] = STATE(32),
    [sym_tt_line_comment] = STATE(32),
    [aux_sym_document_repeat1] = STATE(4),
    [anon_sym_LT_BANG] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_SLASH] = ACTIONS(27),
    [sym_entity] = ACTIONS(29),
    [sym_text] = ACTIONS(29),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(31),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(35),
    [anon_sym_PERCENT_POUND] = ACTIONS(37),
    [sym__implicit_end_tag] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(75),
    [sym_style_start_tag] = STATE(74),
    [sym_self_closing_tag] = STATE(30),
    [sym_end_tag] = STATE(21),
    [sym_erroneous_end_tag] = STATE(7),
    [sym_tt_block] = STATE(7),
    [sym_tt_directive] = STATE(31),
    [sym_tt_comment] = STATE(31),
    [sym_tt_line] = STATE(7),
    [sym_tt_line_directive] = STATE(32),
    [sym_tt_line_comment] = STATE(32),
    [aux_sym_document_repeat1] = STATE(7),
    [anon_sym_LT_BANG] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_SLASH] = ACTIONS(41),
    [sym_entity] = ACTIONS(43),
    [sym_text] = ACTIONS(43),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(31),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(35),
    [anon_sym_PERCENT_POUND] = ACTIONS(37),
    [sym__implicit_end_tag] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(75),
    [sym_style_start_tag] = STATE(74),
    [sym_self_closing_tag] = STATE(30),
    [sym_end_tag] = STATE(45),
    [sym_erroneous_end_tag] = STATE(7),
    [sym_tt_block] = STATE(7),
    [sym_tt_directive] = STATE(31),
    [sym_tt_comment] = STATE(31),
    [sym_tt_line] = STATE(7),
    [sym_tt_line_directive] = STATE(32),
    [sym_tt_line_comment] = STATE(32),
    [aux_sym_document_repeat1] = STATE(7),
    [anon_sym_LT_BANG] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_SLASH] = ACTIONS(27),
    [sym_entity] = ACTIONS(43),
    [sym_text] = ACTIONS(43),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(31),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(35),
    [anon_sym_PERCENT_POUND] = ACTIONS(37),
    [sym__implicit_end_tag] = ACTIONS(47),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_doctype] = STATE(3),
    [sym__node] = STATE(3),
    [sym_element] = STATE(3),
    [sym_script_element] = STATE(3),
    [sym_style_element] = STATE(3),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(75),
    [sym_style_start_tag] = STATE(74),
    [sym_self_closing_tag] = STATE(30),
    [sym_end_tag] = STATE(52),
    [sym_erroneous_end_tag] = STATE(3),
    [sym_tt_block] = STATE(3),
    [sym_tt_directive] = STATE(31),
    [sym_tt_comment] = STATE(31),
    [sym_tt_line] = STATE(3),
    [sym_tt_line_directive] = STATE(32),
    [sym_tt_line_comment] = STATE(32),
    [aux_sym_document_repeat1] = STATE(3),
    [anon_sym_LT_BANG] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_SLASH] = ACTIONS(41),
    [sym_entity] = ACTIONS(49),
    [sym_text] = ACTIONS(49),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(31),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(35),
    [anon_sym_PERCENT_POUND] = ACTIONS(37),
    [sym__implicit_end_tag] = ACTIONS(51),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_doctype] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(73),
    [sym_style_start_tag] = STATE(76),
    [sym_self_closing_tag] = STATE(28),
    [sym_erroneous_end_tag] = STATE(8),
    [sym_tt_block] = STATE(8),
    [sym_tt_directive] = STATE(53),
    [sym_tt_comment] = STATE(53),
    [sym_tt_line] = STATE(8),
    [sym_tt_line_directive] = STATE(15),
    [sym_tt_line_comment] = STATE(15),
    [aux_sym_document_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_entity] = ACTIONS(55),
    [sym_text] = ACTIONS(55),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(15),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(17),
    [anon_sym_PERCENT] = ACTIONS(19),
    [anon_sym_PERCENT_POUND] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(75),
    [sym_style_start_tag] = STATE(74),
    [sym_self_closing_tag] = STATE(30),
    [sym_erroneous_end_tag] = STATE(7),
    [sym_tt_block] = STATE(7),
    [sym_tt_directive] = STATE(31),
    [sym_tt_comment] = STATE(31),
    [sym_tt_line] = STATE(7),
    [sym_tt_line_directive] = STATE(32),
    [sym_tt_line_comment] = STATE(32),
    [aux_sym_document_repeat1] = STATE(7),
    [anon_sym_LT_BANG] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(60),
    [anon_sym_LT_SLASH] = ACTIONS(63),
    [sym_entity] = ACTIONS(66),
    [sym_text] = ACTIONS(66),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(69),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(72),
    [anon_sym_PERCENT] = ACTIONS(75),
    [anon_sym_PERCENT_POUND] = ACTIONS(78),
    [sym__implicit_end_tag] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_doctype] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(73),
    [sym_style_start_tag] = STATE(76),
    [sym_self_closing_tag] = STATE(28),
    [sym_erroneous_end_tag] = STATE(8),
    [sym_tt_block] = STATE(8),
    [sym_tt_directive] = STATE(53),
    [sym_tt_comment] = STATE(53),
    [sym_tt_line] = STATE(8),
    [sym_tt_line_directive] = STATE(15),
    [sym_tt_line_comment] = STATE(15),
    [aux_sym_document_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_LT_BANG] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(86),
    [anon_sym_LT_SLASH] = ACTIONS(89),
    [sym_entity] = ACTIONS(92),
    [sym_text] = ACTIONS(92),
    [anon_sym_LBRACK_PERCENT] = ACTIONS(95),
    [anon_sym_LBRACK_PERCENT_POUND] = ACTIONS(98),
    [anon_sym_PERCENT] = ACTIONS(101),
    [anon_sym_PERCENT_POUND] = ACTIONS(104),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_tt_line_directive_text,
    ACTIONS(109), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(107), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [21] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_tt_line_directive_text,
    ACTIONS(109), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(107), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [42] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_tt_line_directive_text,
    ACTIONS(117), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(115), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [63] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_tt_line_directive_text,
    ACTIONS(117), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(123), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [138] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(135), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [156] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [174] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [228] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [246] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [264] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(163), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [300] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(167), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [318] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [336] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [354] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(179), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(183), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [390] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(179), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(187), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(131), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [444] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(191), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [462] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(195), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [480] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(199), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [498] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(203), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [516] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(207), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(191), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [552] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(127), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [570] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(195), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [588] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(199), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [606] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(139), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [624] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(143), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [642] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(147), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [660] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(151), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(155), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [696] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(159), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(163), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(171), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [750] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(175), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(203), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [786] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(207), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(187), 7,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [822] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 3,
      anon_sym_LT,
      anon_sym_LBRACK_PERCENT,
      anon_sym_PERCENT,
    ACTIONS(183), 7,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
      anon_sym_LBRACK_PERCENT_POUND,
      anon_sym_PERCENT_POUND,
  [840] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_GT,
    ACTIONS(213), 1,
      anon_sym_SLASH_GT,
    ACTIONS(215), 1,
      sym_attribute_name,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [857] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_attribute_name,
    ACTIONS(217), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [872] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_GT,
    ACTIONS(215), 1,
      sym_attribute_name,
    ACTIONS(222), 1,
      anon_sym_SLASH_GT,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [889] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_attribute_name,
    ACTIONS(224), 1,
      anon_sym_GT,
    ACTIONS(226), 1,
      anon_sym_SLASH_GT,
    STATE(57), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [906] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_attribute_name,
    ACTIONS(224), 1,
      anon_sym_GT,
    ACTIONS(228), 1,
      anon_sym_SLASH_GT,
    STATE(55), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [923] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_GT,
    ACTIONS(232), 1,
      sym_attribute_name,
    STATE(62), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [937] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_EQ,
    ACTIONS(234), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [949] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_attribute_name,
    ACTIONS(238), 1,
      anon_sym_GT,
    STATE(64), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [963] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_attribute_name,
    ACTIONS(240), 1,
      anon_sym_GT,
    STATE(64), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [977] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_GT,
    ACTIONS(242), 1,
      sym_attribute_name,
    STATE(64), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [991] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_attribute_value,
    ACTIONS(247), 1,
      anon_sym_SQUOTE,
    ACTIONS(249), 1,
      anon_sym_DQUOTE,
    STATE(70), 1,
      sym_quoted_attribute_value,
  [1007] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_attribute_name,
    ACTIONS(251), 1,
      anon_sym_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1021] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_attribute_value,
    ACTIONS(255), 1,
      anon_sym_SQUOTE,
    ACTIONS(257), 1,
      anon_sym_DQUOTE,
    STATE(84), 1,
      sym_quoted_attribute_value,
  [1037] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1055] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1064] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym__start_tag_name,
    ACTIONS(267), 1,
      sym__script_start_tag_name,
    ACTIONS(269), 1,
      sym__style_start_tag_name,
  [1077] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_EQ,
    ACTIONS(234), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1088] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LT_SLASH,
    ACTIONS(275), 1,
      sym_raw_text,
    STATE(33), 1,
      sym_end_tag,
  [1101] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LT_SLASH,
    ACTIONS(279), 1,
      sym_raw_text,
    STATE(39), 1,
      sym_end_tag,
  [1114] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LT_SLASH,
    ACTIONS(281), 1,
      sym_raw_text,
    STATE(38), 1,
      sym_end_tag,
  [1127] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LT_SLASH,
    ACTIONS(283), 1,
      sym_raw_text,
    STATE(14), 1,
      sym_end_tag,
  [1140] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym__script_start_tag_name,
    ACTIONS(269), 1,
      sym__style_start_tag_name,
    ACTIONS(285), 1,
      sym__start_tag_name,
  [1153] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym__end_tag_name,
    ACTIONS(289), 1,
      sym_erroneous_end_tag_name,
  [1163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(295), 1,
      sym_tt_directive_content,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1189] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(301), 1,
      sym_tt_directive_content,
  [1199] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LT_SLASH,
    STATE(22), 1,
      sym_end_tag,
  [1209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1233] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(305), 1,
      sym_tt_directive_content,
  [1243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_PERCENT_RBRACK,
    ACTIONS(309), 1,
      sym_tt_directive_content,
  [1253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_end_tag,
  [1263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1271] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_end_tag,
  [1281] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LT_SLASH,
    STATE(47), 1,
      sym_end_tag,
  [1291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_SQUOTE,
    ACTIONS(315), 1,
      aux_sym_quoted_attribute_value_token1,
  [1301] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    ACTIONS(317), 1,
      aux_sym_quoted_attribute_value_token2,
  [1311] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_SQUOTE,
    ACTIONS(321), 1,
      aux_sym_quoted_attribute_value_token1,
  [1321] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_DQUOTE,
    ACTIONS(323), 1,
      aux_sym_quoted_attribute_value_token2,
  [1331] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1339] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(327), 1,
      sym__end_tag_name,
  [1349] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_SQUOTE,
  [1356] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym__end_tag_name,
  [1363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      aux_sym_doctype_token1,
  [1370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_GT,
  [1377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_PERCENT_RBRACK,
  [1384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_PERCENT_RBRACK,
  [1391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_GT,
  [1398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_erroneous_end_tag_name,
  [1405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_DQUOTE,
  [1412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_GT,
  [1419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_GT,
  [1426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_GT,
  [1433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_PERCENT_RBRACK,
  [1440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_GT,
  [1447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      ts_builtin_sym_end,
  [1454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_SQUOTE,
  [1461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_DQUOTE,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      sym__doctype,
  [1475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym_erroneous_end_tag_name,
  [1482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      aux_sym_doctype_token1,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_PERCENT_RBRACK,
  [1496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      sym__end_tag_name,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 21,
  [SMALL_STATE(11)] = 42,
  [SMALL_STATE(12)] = 63,
  [SMALL_STATE(13)] = 84,
  [SMALL_STATE(14)] = 102,
  [SMALL_STATE(15)] = 120,
  [SMALL_STATE(16)] = 138,
  [SMALL_STATE(17)] = 156,
  [SMALL_STATE(18)] = 174,
  [SMALL_STATE(19)] = 192,
  [SMALL_STATE(20)] = 210,
  [SMALL_STATE(21)] = 228,
  [SMALL_STATE(22)] = 246,
  [SMALL_STATE(23)] = 264,
  [SMALL_STATE(24)] = 282,
  [SMALL_STATE(25)] = 300,
  [SMALL_STATE(26)] = 318,
  [SMALL_STATE(27)] = 336,
  [SMALL_STATE(28)] = 354,
  [SMALL_STATE(29)] = 372,
  [SMALL_STATE(30)] = 390,
  [SMALL_STATE(31)] = 408,
  [SMALL_STATE(32)] = 426,
  [SMALL_STATE(33)] = 444,
  [SMALL_STATE(34)] = 462,
  [SMALL_STATE(35)] = 480,
  [SMALL_STATE(36)] = 498,
  [SMALL_STATE(37)] = 516,
  [SMALL_STATE(38)] = 534,
  [SMALL_STATE(39)] = 552,
  [SMALL_STATE(40)] = 570,
  [SMALL_STATE(41)] = 588,
  [SMALL_STATE(42)] = 606,
  [SMALL_STATE(43)] = 624,
  [SMALL_STATE(44)] = 642,
  [SMALL_STATE(45)] = 660,
  [SMALL_STATE(46)] = 678,
  [SMALL_STATE(47)] = 696,
  [SMALL_STATE(48)] = 714,
  [SMALL_STATE(49)] = 732,
  [SMALL_STATE(50)] = 750,
  [SMALL_STATE(51)] = 768,
  [SMALL_STATE(52)] = 786,
  [SMALL_STATE(53)] = 804,
  [SMALL_STATE(54)] = 822,
  [SMALL_STATE(55)] = 840,
  [SMALL_STATE(56)] = 857,
  [SMALL_STATE(57)] = 872,
  [SMALL_STATE(58)] = 889,
  [SMALL_STATE(59)] = 906,
  [SMALL_STATE(60)] = 923,
  [SMALL_STATE(61)] = 937,
  [SMALL_STATE(62)] = 949,
  [SMALL_STATE(63)] = 963,
  [SMALL_STATE(64)] = 977,
  [SMALL_STATE(65)] = 991,
  [SMALL_STATE(66)] = 1007,
  [SMALL_STATE(67)] = 1021,
  [SMALL_STATE(68)] = 1037,
  [SMALL_STATE(69)] = 1046,
  [SMALL_STATE(70)] = 1055,
  [SMALL_STATE(71)] = 1064,
  [SMALL_STATE(72)] = 1077,
  [SMALL_STATE(73)] = 1088,
  [SMALL_STATE(74)] = 1101,
  [SMALL_STATE(75)] = 1114,
  [SMALL_STATE(76)] = 1127,
  [SMALL_STATE(77)] = 1140,
  [SMALL_STATE(78)] = 1153,
  [SMALL_STATE(79)] = 1163,
  [SMALL_STATE(80)] = 1171,
  [SMALL_STATE(81)] = 1181,
  [SMALL_STATE(82)] = 1189,
  [SMALL_STATE(83)] = 1199,
  [SMALL_STATE(84)] = 1209,
  [SMALL_STATE(85)] = 1217,
  [SMALL_STATE(86)] = 1225,
  [SMALL_STATE(87)] = 1233,
  [SMALL_STATE(88)] = 1243,
  [SMALL_STATE(89)] = 1253,
  [SMALL_STATE(90)] = 1263,
  [SMALL_STATE(91)] = 1271,
  [SMALL_STATE(92)] = 1281,
  [SMALL_STATE(93)] = 1291,
  [SMALL_STATE(94)] = 1301,
  [SMALL_STATE(95)] = 1311,
  [SMALL_STATE(96)] = 1321,
  [SMALL_STATE(97)] = 1331,
  [SMALL_STATE(98)] = 1339,
  [SMALL_STATE(99)] = 1349,
  [SMALL_STATE(100)] = 1356,
  [SMALL_STATE(101)] = 1363,
  [SMALL_STATE(102)] = 1370,
  [SMALL_STATE(103)] = 1377,
  [SMALL_STATE(104)] = 1384,
  [SMALL_STATE(105)] = 1391,
  [SMALL_STATE(106)] = 1398,
  [SMALL_STATE(107)] = 1405,
  [SMALL_STATE(108)] = 1412,
  [SMALL_STATE(109)] = 1419,
  [SMALL_STATE(110)] = 1426,
  [SMALL_STATE(111)] = 1433,
  [SMALL_STATE(112)] = 1440,
  [SMALL_STATE(113)] = 1447,
  [SMALL_STATE(114)] = 1454,
  [SMALL_STATE(115)] = 1461,
  [SMALL_STATE(116)] = 1468,
  [SMALL_STATE(117)] = 1475,
  [SMALL_STATE(118)] = 1482,
  [SMALL_STATE(119)] = 1489,
  [SMALL_STATE(120)] = 1496,
  [SMALL_STATE(121)] = 1503,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_line_comment, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_line_comment, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_line_directive, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_line_directive, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_line, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_line, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_directive, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_directive, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_comment, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_comment, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_directive, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_directive, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_block, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_block, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_comment, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_comment, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_line_directive, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_line_directive, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tt_line_comment, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tt_line_comment, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [355] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
  ts_external_token_tt_directive_content = 9,
  ts_external_token_tt_line_directive_text = 10,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_tt_directive_content] = sym_tt_directive_content,
  [ts_external_token_tt_line_directive_text] = sym_tt_line_directive_text,
};

static const bool ts_external_scanner_states[13][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_tt_directive_content] = true,
    [ts_external_token_tt_line_directive_text] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_tt_line_directive_text] = true,
  },
  [5] = {
    [ts_external_token_comment] = true,
    [ts_external_token_tt_line_directive_text] = true,
  },
  [6] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token_comment] = true,
    [ts_external_token_tt_directive_content] = true,
  },
  [11] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [12] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ttk_external_scanner_create(void);
void tree_sitter_ttk_external_scanner_destroy(void *);
bool tree_sitter_ttk_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ttk_external_scanner_serialize(void *, char *);
void tree_sitter_ttk_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ttk(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ttk_external_scanner_create,
      tree_sitter_ttk_external_scanner_destroy,
      tree_sitter_ttk_external_scanner_scan,
      tree_sitter_ttk_external_scanner_serialize,
      tree_sitter_ttk_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ttk",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
